### ISSUE TITLE
Decode.string fails on strings with datetime

### ISSUE THREAD

**Issue by MangelMaxime** [thoth-org/Thoth.Json.Net#13]
Original issue: https://github.com/MangelMaxime/Thoth/issues/142
by @dbrattli 

Looks like `Decode.string` fails with this string. Using Thoth.Json.Net (3.1) Newtonsoft.Json (12.0.1). Anyone that can repro this?

```fs
Decode.fromString Decode.string "\"2018-08-06T10:06:40.000\""
```

```
"Error at: `$` Expecting a string but instead got: "2018-08-06T10:06:40""
```

Probably because it's a datetime, perhaps related to https://stackoverflow.com/questions/11856694/json-net-disable-the-deserialization-on-datetime

**Comment by MangelMaxime** [comment]
This problem is due to Newtonsoft trying to be "smart" and detecting a DateTime format and so casting it to a DateTime.

I will see if I can quickly implement a fix to prevent Newtonsoft from detecting DateTime format.

**Comment by dbrattli** [comment]
Good. In my application I'm parsing a metadata field with an object of string/string, so not possible for me to know if I should expect a DateTime there or not since there's no schema for the metadata. E.g:

```json
{
        "id": 123,
        "name": "name",
        "metadata": {
          "current_operator": "XYZ",
          "elevation_type": "SITE",
          "elevation_update_date": "2018-08-06T10:06:40.000",
          "elevation_value": "25.0",
          "elevation_value_unit": "m",
        },
        "createdTime": 1554989112935,
        "lastUpdatedTime": 1554990114723
      },
```

**Comment by MangelMaxime** [comment]
If you are using manual decoders, you can implement a permissive decoder for this specific field.

If this is a `string` detected just parse it as a string and if you detect a `DateTime` then cast it to a `string`. But it is not perfect.

I am taking a look at this issue because this is not the first time that this behaviour from Newtonsoft is causing us a problem.

**Comment by dbrattli** [comment]
Yes, not perfect as casting the date back to string will write the string as "08/06/2018 10:06:40" which is different from the original string "2018-08-06T10:06:40.000".

**Comment by dbrattli** [comment]
https://github.com/JamesNK/Newtonsoft.Json/issues/862

**Comment by MangelMaxime** [comment]
It should be fixed in version `3.2.0`. 

You probably need for Nuget to do its job :)

**Comment by dbrattli** [comment]
That is great new! Thank you @MangelMaxime for fixing so quickly. It was a serious bug imo since even manual decoders would fail with the "wrong" input, and my library suddenly started failing yesterday when handling a new source.

**Comment by MangelMaxime** [comment]
> It was a serious bug imo since even manual decoders would fail with the "wrong" input, and my library suddenly started failing yesterday when handling a new source.

Indeed, I knew about this problem but always reported the fix to later because no one had it and I had other stuff to do. At least, I can remove it from my todo list now ^^
