### ISSUE TITLE
Helps needed to package correctly Thoth.Json.Net

### ISSUE THREAD

**Issue by MangelMaxime** [thoth-org/Thoth.Json.Net#21]
*Disclaimer: I don't know much about how `nuspec` and `nuget` package works. In general, they just work for me so I am fine. But with `Thoth.Json.Net` I have a more complex package  and I am a bit lost.*

@forki this issue is about my call for help on Twitter. I tried to sum up the different problem I have and what actions have been taken when so you can have a global vision of the situation. Sorry for the long issue but I tried to be as explicit as possible.

**Problem n°1**: The dependencies list doesn't reflect the difference depending on the targetted framework.

Since several version `Thoth.Json.Net` have the following depencies list:

**Version 3.4.0**
<img width="368" alt="Capture d’écran 2019-06-11 à 09 23 06" src="https://user-images.githubusercontent.com/4760796/59251680-b3871400-8c2a-11e9-839e-edabf3ce7bd9.png">

Instead of something like that:

**Version 3.0.0-beta-001**
<img width="304" alt="Capture d’écran 2019-06-11 à 09 23 28" src="https://user-images.githubusercontent.com/4760796/59251684-b5e96e00-8c2a-11e9-895d-757d5837e994.png">

This problem appeared when I tried to lower `Newtonsoft.Json` dependency to `>= 11.0.2` instead of `12.0.1`.

At that time, I switched from `dotnet pack` to `paket pack` using `paket.template` in **project mode** so it had the correct dependency for `Newtonsoft.Json` based on `paket.dependencies`.

In the past, @forki mentionned that if we didn't need different transitive deps in different framework it was "ok". [Comment](https://github.com/thoth-org/Thoth.Json.Net/issues/3#issuecomment-483982682)

However now, I need different deps depending on the Framework.

<img width="362" alt="Capture d’écran 2019-06-11 à 09 29 41" src="https://user-images.githubusercontent.com/4760796/59252042-77a07e80-8c2b-11e9-8b31-5579170ac375.png">

See how **.NETStandard 2.0** require `Fable.Core` now while **.NETFramework 4.6** doesn't use it because `Fable.Core` is not available here and was generating exceptions.

In order to archieved this result, I use `paket.template` in **file mode**. [Source](https://github.com/thoth-org/Thoth.Json.Net/blob/e5f15274a58760fa8d914942dde3bf3652861ff1/src/paket.template)

**Problem n°2**: It seems that even if we have `Newtonsoft.Json >= 11.0.2` the dll was using/required `12.0.0`.

@bentayloruk raised an issue about that https://github.com/thoth-org/Thoth.Json.Net/issues/18 and because I didn't see any problem with releasing a new version solving his problem we added `lowest_matching:true` to [paket.dependencies](https://github.com/thoth-org/Thoth.Json.Net/blob/e5f15274a58760fa8d914942dde3bf3652861ff1/paket.dependencies#L7)

**Problem n°3**: The `AssemblyInfo` of version `3.5.0-beta-001` seems to say that the `AssemblyVersion` is 1.0.0 which seems wrong.

> I'm having some issues, but not sure why they are happening yet.  Will investigate.

> Side question, 3.5.0 beta 1 is `1.0.0.0` in all of the assembly version attributes.  Is that intentional?
> <img width="739" alt="image" src="https://user-images.githubusercontent.com/189409/59165139-84f72500-8ad4-11e9-9fce-7bbfb1e7db76.png">

_Originally posted by @bentayloruk in https://github.com/thoth-org/Thoth.Json.Net/pull/19#issuecomment-500251013_

I suppose this is related to the changes I made when using `paket.template` in **file mode**. When doing so because the **file mode** of paket was asking the same info that I already had in my `fsproj` I removed them from that last file. 

[Diff of the changes made](https://github.com/thoth-org/Thoth.Json.Net/commit/3c18568cc9f356e9fc5907032389c549574e0138#diff-ff6fc11c05b56740bf3cbea14ceab332)

My question is should we keep the info in both file? Should I use FAKE to generate the `AssymblyInfo` file and how can I use that generated file?

**Problem n°4**: Should we set an upper version restriction on the depencies?

<img width="362" alt="Capture d’écran 2019-06-11 à 09 29 41" src="https://user-images.githubusercontent.com/4760796/59254403-6312b500-8c30-11e9-8660-5d9916d9f76f.png">

As you can see here `Newtonsoft.Json` is marked as `>= 11.0.2` so people can use version `12+` of it.

While `Fable.Core` is marked as `(>= 3.0.0 && < 4.0.0)`. What is the correct way to restrict dependencies?

**Comment by MangelMaxime** [comment]
Friendly ping @forki :)

**Comment by forki** [comment]
> While Fable.Core is marked as (>= 3.0.0 && < 4.0.0). What is the correct way to restrict dependencies?

I think given that Fable.Core changes were rather breaking in the past I think this is fair. The only downside is that you need to publish an update here as soon as Fable.Core goes 4.0 (probably even when it releases alpha)

Regarding https://github.com/thoth-org/Thoth.Json.Net/commit/3c18568cc9f356e9fc5907032389c549574e0138#diff-ff6fc11c05b56740bf3cbea14ceab332  - yes this is a bit unfortunate but type file does not use the project settings. You need to be very explicit.

**Comment by MangelMaxime** [comment]
> I think given that Fable.Core changes were rather breaking in the past I think this is fair. The only downside is that you need to publish an update here as soon as Fable.Core goes 4.0 (probably even when it releases alpha)

I am ok with that, this is already what I had to do in the past in order to support the new API

> Regarding 3c18568#diff-ff6fc11c05b56740bf3cbea14ceab332 - yes this is a bit unfortunate but type file does not use the project settings. You need to be very explicit.

I don't have a problem with moving the info from the `fsproj` to `paket.template`. My concerns is more about the fact that the `AssemblyInfo` seems wrong.

Do I have to put the information in both place? Do I have to generate the `AssemblyInfo` myself and if yes I do I package the nuget using this generated file?

**Comment by forki** [comment]
> My concerns is more about the fact that the AssemblyInfo seems wrong.

yeah that's even more unfortunate. The compiler uses he AssemblInfo and/or the fsproj settings. It does not know about paket template files. So you clearly need to change fsproj and/or AssemblyInfo.

And then the type file needs it as well since it does not make any connection to projects. It's basically a completely independent approach that you can use to package stuff that may not even come from any fsproj or csproj

**Comment by MangelMaxime** [comment]
Ok thank you so I will:

- Keep using `paket.template`
- Generate the `AssemblyInfo` file
- Keep `Fable.Core` restriction
- Open `FSharp.Core` to be something like `>= 4.6.2`

**Comment by matthid** [comment]
Sorry for not responding sooner but there are a lot of mixed questions in that which takes a while to respond properly.
In Short:
- AssemblyVersion has nothing to do with package version
- In .NET SDK they use the same field (`Version`) in msbuild for AssemblyVersion and PackageVersion
- Paket doesn't really support different versions based on framework at this time
- There is an open issue in the compiler not setting FileVersion (explorer hover/details page), this is not technically required anywhere so the impact is low (but can lead to confustion). Always check if reflection tools like dotpeek

My recommendation: 
- Do not use `paket pack`, use `dotnet pack` and set the msbuild properties as recommended. In fact you can always use environment variables for example from the FAKE script (for example set `Version` environment variable and msbuild will pick it up)
- Do not use AssemblyInfo any longer. Set the corresponding msbuild variables as needed (if you need company and description information)


This is very short, feel free to further refine questions regarding that ;)

**Comment by MangelMaxime** [comment]
> Sorry for not responding sooner but there are a lot of mixed questions in that which takes a while to respond properly.

No problem, I know that there is a lot but I am discovering all these problems ^^

> Do not use paket pack, use dotnet pack and set the msbuild properties as recommended. In fact you can always use environment variables for example from the FAKE script (for example set Version environment variable and msbuild will pick it up)

I  made the switch to `paket pack` because `dotnet pack` wasn't picking the correct version of `Newtonsoft.Json`. It was picking up `>= 12.0.1` instead of `>= 11.0.2`.

In theory, if you know how to fix this problem when using `dotnet pack` it should be ok. 

And also, if `dotnet pack` support different deps depending on the framework.

**Comment by MangelMaxime** [comment]
Also, is it possible to mark `Fable.Core` with `(>= 3.0.0 && < 4.0.0)` version when using `dotnet pack`? If yes, how ?

**Comment by matthid** [comment]
Yes dotnet pack supports all of this, but the combination with paket complicates some of these. the easiest is to overwrite paket by adding dependencies directly into the project file `<PackageReference Condition="'$(TargetFramework)' == 'net46'" Name="Newtonsoft.Json" Version="11.0.2" />`

This should in theory overwrite paket in this scenario. For upper bounds of dependencies you need to consult the docs as I don't recall the syntax. I think it's similar to `Version="[3.0,4.0["`.

Note that you still use paket but overwrite it in some occasions.

Warning: I wrote this on mobile and without google so there might be syntax problems or fields called differently

**Comment by MangelMaxime** [comment]
Hum ok thank you both will try to make something from all this discussion and see how it goes :)

**Comment by bentayloruk** [comment]
@MangelMaxime I will test the package again when you think you're ready.  I don't think we can rely on the results of my last test, given that the `AssemblyVersion` is incorrect.  I must admit to not being aware of all the nuances around assembly resolution in .NET Core and a lot of the information in this issue, so I am learning a lot too!

**Comment by MangelMaxime** [comment]
@forki @matthid Thank you both

I think I manage to fix all the issues I had.

In the end, here are the action I took:

- I remove `paket.template`
- Use `dotnet pack` 
- Override `Fable.Core` dependency 
    - Use `<PackageReference Condition="'$(TargetFramework)' == 'netstandard2.0'" Include="Fable.Core" Version="[3.0,4.0)" />` in the `*fsproj`
    - Use `nuget Fable.Core ~> 3 framework: netstandard2.0` in `paket.dependencies`

I now have the proper deps displayed on nuget:

<img width="457" alt="Capture d’écran 2019-06-24 à 12 07 52" src="https://user-images.githubusercontent.com/4760796/60010750-bb0dda80-9678-11e9-901f-13dc580b6ae6.png">

I also tested the package againt Bookstore and it was working so hopefully it's ok for everyone now.

@bentayloruk You should be able to check again the package againt your problem if you need. It should still be compiled againt the `lower` version of Newtonsoft because I kept it in `paket.dependencies`.

**Comment by bentayloruk** [comment]
@MangelMaxime this is great and I will try it out at my end as soon as I can.  It wont be until next week now as I'm off this week, but it all sounds good to me.  Based on my understanding of .NET Core assembly binding, compiling against the lower version will offer the most flexibility to consumers in .NET Core because it should work with compatible newer versions of Newtonsoft.Json, whereas it would not support working with older versions as it was before.
