### ISSUE TITLE
Handling of Enums

### ISSUE THREAD

**Issue by SCullman** [thoth-org/Thoth.Json.Net#25]
Currently encoding and decoding of ordinary `enum`s like `System.DayOfTheWeek` require own extra coders, e.g.
```fsharp
module Encode =
   let dayofWeek (value: System.DayOfWeek) : JsonValue =
       LanguagePrimitives.EnumToValue (value)
       |>JValue :> JsonValue


module Decode =
    module Helpers =
        let inline isInteger (token: JsonValue) = not(isNull token) && (token.Type = JTokenType.Integer)
        let inline isString (token: JsonValue) = not(isNull token) && token.Type = JTokenType.String
        let inline asString (token: JsonValue): string = token.Value<string>()
    
    let dayofWeek : Decoder<System.DayOfWeek> =
        fun path token ->
            if Helpers.isInteger token then
                // TODO: Is not enough to convert to int directly? Maybe these checks hurt performance?
                let value = token.Value<decimal> ()
                if value >= (decimal System.Int32.MinValue) && value <= (decimal System.Int32.MaxValue) then
                    Ok (LanguagePrimitives.EnumOfValue ((int32) value))
                else
                    (path, BadPrimitiveExtra("an int", token, "Value was either too large or too small for an int")) |> Error
            elif Helpers.isString token then
                match System.Int32.TryParse (Helpers.asString token, NumberStyles.Any, CultureInfo.InvariantCulture) with
                | true, x -> Ok <| LanguagePrimitives.EnumOfValue(x)
                | _ -> (path, BadPrimitive("an int", token)) |> Error
            else
                (path, BadPrimitive("an int", token)) |> Error

```

This works pretty good, however I would love to have generic Enum support, either direclty in Thoth.Json or as extra coder.

This naive approach fail:
```fsharp
module Encode =

   let enumInt (value: 'T when 'T:enum<int>) : JsonValue =
       LanguagePrimitives.EnumToValue (value)
       |>JValue :> JsonValue

module Decode =
    module Helpers =
        let inline isInteger (token: JsonValue) = not(isNull token) && (token.Type = JTokenType.Integer)
        let inline isString (token: JsonValue) = not(isNull token) && token.Type = JTokenType.String
        let inline asString (token: JsonValue): string = token.Value<string>()
    
    let enumInt : Decoder<'T> when 'T:enum<int> =
        fun path token ->
            if Helpers.isInteger token then
                // TODO: Is not enough to convert to int directly? Maybe these checks hurt performance?
                let value = token.Value<decimal> ()
                if value >= (decimal System.Int32.MinValue) && value <= (decimal System.Int32.MaxValue) then
                    Ok (LanguagePrimitives.EnumOfValue ((int32) value))
                else
                    (path, BadPrimitiveExtra("an int", token, "Value was either too large or too small for an int")) |> Error
            elif Helpers.isString token then
                match System.Int32.TryParse (Helpers.asString token, NumberStyles.Any, CultureInfo.InvariantCulture) with
                | true, x -> Ok <| LanguagePrimitives.EnumOfValue(x)
                | _ -> (path, BadPrimitive("an int", token)) |> Error
            else
                (path, BadPrimitive("an int", token)) |> Error
```
While the encoders and decoders work, they cannot be added `withCustom`, and I also failt adding them directly in Thoth.Json.Net.

It worked before in 2.x, maybe this just a special case of #9, where all unknown types case were handled by NewtonSoft.Json.

**Comment by MangelMaxime** [comment]
> where all unknown types case were handled by NewtonSoft.Json.

Yes, I think before NewtonSoft.Json was doing the job for us on the server-side.

The problem with supporting enum is not the server-side but Fable side because it doesn't have yet all the reflection API info needed (I still need to check if that's still the case).

Related issue: https://github.com/MangelMaxime/Thoth/issues/161

I will try to take a look at the situation this week because you are several asking for it. And will also, make writing low-level decoder easier by making public the helpers module. Because I have it copied myself into several projects so it's worth than exposing it by default as it can go out of sync.

**Comment by SCullman** [comment]
Thank you. 
I would appreciate if the server side is capable to support the whole .Net types including Enums. For the Fable side, I would then fake my own matching types.

If you need any help, for example to write some tests, just let me know.

**Comment by MangelMaxime** [comment]
> I would appreciate if the server side is capable to support the whole .Net types including Enums. For the Fable side, I would then fake my own matching types.

I understand that wish, but I can't make Thoth.Json and Thoth.Json.Net support different things because they are supposed to be replacement of each others depending on the runtime.

The reason, being otherwise you will have code working differently depending on the runtime and it goes against the security provided by Thoth.Json.

But, when something is missing my goal is to add it to both so in theory at some point we will support everything in both runtimes :)

**Comment by SCullman** [comment]
> I understand that wish, but I can't make Thoth.Json and Thoth.Json.Net support different things because they are supposed to be replacement of each others depending on the runtime.

Runtime is not only SAFE stack, e.g. I am supporting a .Net Framework based CMS, written in C#.
I wanna just pass some POCOs to fable, and then I don't want/need to share code between runtime and fable. 

IMHO it is totally fine to have a C# Poco in runtime 
```csharp
class PersonPoco{
  public string FirstName {get;set;}
  public string LastName {get;set;}
}
```
which maps then in Fable with
```fsharp
type Person = 
     { FirstName:string; 
       LastName:string }
```
This worked before. It was even possible to mix C# Pocos with F# types, e.g. `type Person = Poco of PersonPoco` in Runtime.  
Now it is required to map everything. I accepted that, too. But sometimes I wish the former comfort back. 
(And this should be better discussed in #9)

**Comment by MangelMaxime** [comment]
Ooops, I completely forget about #9 ...  

It's sometimes hard to remember that not everyone has the same needs/workflow. :) I will see to fix enum support first and look at the C# / F# mix and see if I can find a solution to make it work out the box or with minimal code on your side.

**Comment by SCullman** [comment]
I always thought to serialize the value, however it is much easier with `.ToString()` and `Enum.Parse`

**Comment by SCullman** [comment]
Too early to be happy:
```fsharp
printfn "%s" (System.DayOfWeek.Tuesday.ToString())
// "2" in Fable, "Tuesday" in Runtime
```

**Comment by SCullman** [comment]
Enums are now treated as ints :-)
