### ISSUE TITLE
Problems with FSharp.Core dependency

### ISSUE THREAD

**Issue by alfonsogarciacaro** [thoth-org/Thoth.Json.Net#3]
Not sure if it's related with the problems you had in https://github.com/SAFE-Stack/SAFE-BookStore/pull/388 but there seems to be an issue with the FSharp.Core dependency in the Thoth.Json.Net package. This is causing an issue in one of my projects when trying to use Thoth.Json.Net 3.0.0-beta-005.

In Nuget, the version of the FSharp.Core dependency is 0.0.0:

![image](https://user-images.githubusercontent.com/8275461/56144136-2153ee00-5fa2-11e9-9926-60a7489800b6.png)

@forki do you have any idea why this happens? Maybe it's related with the multiple target frameworks?

**Comment by forki** [comment]
What is the issue?

Alfonso Garcia-Caro <notifications@github.com> schrieb am Mo., 15. Apr.
2019, 17:18:

**Comment by alfonsogarciacaro** [comment]
The FSharp.Core dependency is >= 0.0.0 which is quite weird. Anyways, I managed to fix the issue in my project and maybe it was not related to Thoth.Json.Net after all. Apparently Paket can resolve different versions of the same package in the same group (FSharp.Core in this case) if multiple frameworks are specified which I didn't know.

Seems to be fixed by pinpointing FSharp.Core's version in paket.dependencies.

**Comment by forki** [comment]
Yes if target frameworks are different then it does that. But usually (like
99 percent of the cases) you don't want that to happen. In the 1 percent
it's absolutely needed.

Alfonso Garcia-Caro <notifications@github.com> schrieb am Di., 16. Apr.
2019, 01:21:

**Comment by MangelMaxime** [comment]
So is there something I need to change?

And if yes what? :)

**Comment by forki** [comment]
Do you have different target frameworks? If so, why?

**Comment by forki** [comment]
the question was more: do your lib itself needs transitive deps in different frameworks? I guess not. so all should be well

**Comment by MangelMaxime** [comment]
I guess no too. So I can just close the issue?

**Comment by forki** [comment]
yeah

**Comment by MangelMaxime** [comment]
Thank you
