### ISSUE TITLE
Numbers are encoded as strings

### ISSUE THREAD

**Issue by huwmanatee** [thoth-org/Thoth.Json.Net#31]
Hi,

I just ran into an issue when attempting to decode json (Encoded with Thoth.Json.Net) using Elm's decoders: Thoth.Json.Net appears to encode numbers as strings whereas Elm's decoder is expecting number within the json.

Some code from Encode.fs:

`let uint64 (value : uint64) : JsonValue = 
    JValue(value.ToString(CultureInfo.InvariantCulture)) :> JsonValue`

Is this an oversight or by design?
My expectation was that numbers would be encoded without quotes to the json.

**Comment by MangelMaxime** [comment]
I think we decided to encode the numbers as a string because some of them are not valid JavaScript numbers (out of range).

And I probably just applied the rule to all the numbers by default when mutualizing the [decoder code](https://github.com/thoth-org/Thoth.Json.Net/blob/master/src/Decode.fs#L149-L171) which accept both representation as a valid number.

**Comment by aparent-emgs** [comment]
What if one wants to Encode JSON for a system that expects numbers to be actual numbers?

**Comment by huwmanatee** [comment]
I've created the following module:
![image](https://user-images.githubusercontent.com/34071929/72543234-1bbb6980-388e-11ea-8126-73eb3f522d04.png)

If you open this module after your `open Thoth.Json.Net` statement then it will override the functions with the ones defined in the module. This works for the server side, I haven't checked how numbers are encoded with Thoth.Json client side library, I'm using Elm client side.

Works for me, I don't expect the Thoth.Json library to change the way it encodes anytime soon as that would probably be a breaking change.

**Comment by aparent-emgs** [comment]
Ye that's what I was thinking of doing. And I guess if one wants to use those for auto encoders he can just add them to the extra encoders to replace the default ones.

**Comment by huwmanatee** [comment]
I explicitly control the encode / decode chain so I avoid the serializer resolved by the context. You don't know when it is using the extra coder you provided or not, except in the case where it fails to encode/decode the type. I also don't want the serializer to throw exceptions.
So I write to the output stream directly like this:
![image](https://user-images.githubusercontent.com/34071929/72545447-b49fb400-3891-11ea-98df-6696b56869a4.png)

Codec here is a library I ported from Elm that enables one to declare a symmetrical encoder / decoder pair in one go, rather than defining the encoder and decoder separately. 

You could easily change this code to just use the Thoth.Json.Net encoder.

**Comment by MangelMaxime** [comment]
> Ye that's what I was thinking of doing. And I guess if one wants to use those for auto encoders he can just add them to the extra encoders to replace the default ones.

If I remember correctly, you can't yet override the default coders for auto encoders. We are looking at extra coders only if the type is unknown in the default one. It's something I want to change in a next major version of Thoth.Json(.Net)

**Comment by aparent-emgs** [comment]
Thank you for the clarification! This issue is not yet a problem for me as we are not using Thoth to encode data in any back-end code just yet, but I will keep all of this in mind for when we get there.

**Comment by MangelMaxime** [comment]
I am closing because I don't think this will be fixed in Thoth.Json.Net

The new rewrite of Thoth.Json will be a good opportunity to rethink the number representation if needed.
