### ISSUE TITLE
NullRef in an optional decoder

### ISSUE THREAD

**Issue by mnebes** [thoth-org/Thoth.Json.Net#53]
Hi,

I have encountered the following inconsistency that I think might be a bug in Thoth.Json. Let's say we have an optional object in a JSON document. The field that holds it is decoded as optional. However, if I access some values of the object in its decoder (other than assigning them to some fields) the decoder crashes with a nullref. This happens _only_ if the json document contains a key for the object that is assigned to a null literal. Here is a short repro of this behavior: https://gist.github.com/mnebes/12e51348d76440c5106202315494272a

I _think_ one could fix that by slightly reordering the `decodeMaybeNull` function to first check for the null literal and only after that invoke the decoder like so:

```diff
-    let private decodeMaybeNull path (decoder : Decoder<'T>) value =
-       // The decoder may be an option decoder so give it an opportunity to check null values
-        match decoder path value with
-        | Ok v -> Ok(Some v)
-        | Error _ when Helpers.isNullValue value -> Ok None
-        | Error er -> Error er
+    let private decodeMaybeNull path (decoder : Decoder<'T>) value =
+        // The decoder may be an option decoder so give it an opportunity to check null values
+        if Helpers.isNullValue value then
+            Ok None
+        else
+            match decoder path value with
+            | Ok v -> Ok(Some v)
+            | Error er -> Error er
```

This works, but judging by the comment this is on purpose that the decoder is executed (though I can't quite imagine a situation where that would be effectively different than "short-circuiting" here?), so if you have any advice as to how to proceed it would be highly appreciated!

**Comment by MangelMaxime** [comment]
Hello,

I think you could probably go away from this error by using `Decode.andThen` or `Decode.map`.
But I agree that the bug is due to how Thoth.Json resolve the situation you described.

Indeed, even if the value is `null` with the current implementation the `decoder` is still evaluated. By using the `if` statement that you propose we can guard the decoder evaluation to happen only if there is an actual value and not `null`.

**Comment by MangelMaxime** [comment]
I published a new version with the fix, thank you

**Comment by mnebes** [comment]
Awesome, many thanks! 🎉
